=== berk-tas/demo-config-platform/packages/config-contracts/generated/json-schema/assets.json
{
  "$id": "https://demo.local/config/1.0.0/assets.json",
  "title": "assets",
  "version": "1.0.0",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "depositSuspended": {
        "type": "boolean"
      },
      "withdrawSuspended": {
        "type": "boolean"
      },
      "symbol": {
        "type": "string",
        "minLength": 1
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "icon": {
        "type": "string",
        "minLength": 1
      },
      "coinGeckoId": {
        "type": "string",
        "minLength": 1
      },
      "minimumAmountToSweep": {
        "type": "string",
        "minLength": 1
      },
      "gasLimit": {
        "type": "string",
        "minLength": 1
      },
      "networks": {
        "type": "object",
        "propertyNames": {
          "type": "string",
          "minLength": 1
        },
        "additionalProperties": {
          "type": "object",
          "properties": {
            "chain": {
              "type": "string",
              "minLength": 1
            },
            "contractAddress": {
              "type": "string",
              "minLength": 1
            },
            "decimals": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            }
          },
          "required": [
            "chain",
            "decimals"
          ],
          "additionalProperties": false
        }
      },
      "isNative": {
        "type": "boolean"
      },
      "assetAddress": {
        "type": "string"
      },
      "assetType": {
        "type": "string",
        "minLength": 1
      },
      "decimals": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "displayDecimals": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "isHidden": {
        "type": "boolean"
      }
    },
    "required": [
      "depositSuspended",
      "withdrawSuspended",
      "symbol",
      "name",
      "icon",
      "coinGeckoId",
      "minimumAmountToSweep",
      "gasLimit",
      "networks",
      "isNative",
      "assetAddress",
      "assetType",
      "decimals",
      "displayDecimals",
      "isHidden"
    ],
    "additionalProperties": false
  }
}

=== berk-tas/demo-config-platform/values/1.0.0/assets.json
[
  {
    "depositSuspended": true,
    "withdrawSuspended": false,
    "symbol": "BTC",
    "name": "Bitcoin",
    "icon": "https://assets.demo.local/icons/btc.svg",
    "coinGeckoId": "bitcoin",
    "minimumAmountToSweep": "0.0005",
    "gasLimit": "0",
    "networks": {
      "bitcoin": {
        "chain": "bitcoin",
        "decimals": 8
      }
    },
    "isNative": true,
    "assetAddress": "",
    "assetType": "native",
    "decimals": 8,
    "displayDecimals": 8,
    "isHidden": false
  },
  {
    "depositSuspended": false,
    "withdrawSuspended": false,
    "symbol": "USDT",
    "name": "Tether USD",
    "icon": "https://assets.demo.local/icons/usdt.svg",
    "coinGeckoId": "tether",
    "minimumAmountToSweep": "10",
    "gasLimit": "100000",
    "networks": {
      "ethereum": {
        "chain": "ethereum",
        "contractAddress": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
        "decimals": 6
      },
      "tron": {
        "chain": "tron",
        "contractAddress": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
        "decimals": 6
      }
    },
    "isNative": false,
    "assetAddress": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    "assetType": "erc20",
    "decimals": 6,
    "displayDecimals": 2,
    "isHidden": false
  },
  {
    "depositSuspended": false,
    "withdrawSuspended": false,
    "symbol": "ARB",
    "name": "Arbitrum",
    "icon": "https://assets.coingecko.com/coins/images/16547/large/arb.jpg",
    "coinGeckoId": "arbitrum",
    "minimumAmountToSweep": "0.1",
    "gasLimit": "0",
    "networks": {
      "arbitrum": {
        "chain": "arbitrum",
        "contractAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
        "decimals": 18
      }
    },
    "isNative": false,
    "assetAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
    "assetType": "erc20",
    "decimals": 18,
    "displayDecimals": 6,
    "isHidden": false
  },
  {
    "depositSuspended": false,
    "withdrawSuspended": false,
    "symbol": "AAARB",
    "name": "Arbitrum",
    "icon": "https://assets.coingecko.com/coins/images/16547/large/arb.jpg",
    "coinGeckoId": "arbitrum",
    "minimumAmountToSweep": "0.1",
    "gasLimit": "0",
    "networks": {
      "arbitrum": {
        "chain": "arbitrum",
        "contractAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
        "decimals": 18
      }
    },
    "isNative": false,
    "assetAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
    "assetType": "erc20",
    "decimals": 18,
    "displayDecimals": 6,
    "isHidden": false
  },
  {
    "depositSuspended": false,
    "withdrawSuspended": false,
    "symbol": "hmm",
    "name": "Arbitrum",
    "icon": "https://assets.coingecko.com/coins/images/16547/large/arb.jpg",
    "coinGeckoId": "arbitrum",
    "minimumAmountToSweep": "0.1",
    "gasLimit": "0",
    "networks": {
      "arbitrum": {
        "chain": "arbitrum",
        "contractAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
        "decimals": 18
      }
    },
    "isNative": false,
    "assetAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
    "assetType": "erc20",
    "decimals": 18,
    "displayDecimals": 6,
    "isHidden": false
  },
  {
    "depositSuspended": false,
    "withdrawSuspended": false,
    "symbol": "hmmmm",
    "name": "Arbitrum",
    "icon": "https://assets.coingecko.com/coins/images/16547/large/arb.jpg",
    "coinGeckoId": "arbitrum",
    "minimumAmountToSweep": "0.1",
    "gasLimit": "0",
    "networks": {
      "arbitrum": {
        "chain": "arbitrum",
        "contractAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
        "decimals": 18
      }
    },
    "isNative": false,
    "assetAddress": "0x912CE59144191C1204E64559FE8253a0e49E6548",
    "assetType": "erc20",
    "decimals": 18,
    "displayDecimals": 6,
    "isHidden": false
  }
]
